image: neatsolutionslab/jdk:11.0.0open

before_script:
- source ~/.sdkman/bin/sdkman-init.sh

build-on-java11.0.0:
  image: neatsolutionslab/jdk:11.0.0open
  stage: build
  tags:
  - docker
  script:
  - mvn package -Dmaven.test.skip=true

test-on-java11.0.0:
  image: neatsolutionslab/jdk:11.0.0open
  stage: test
  tags:
  - docker
  script:
  - mvn verify
