image: registry.gitlab.com/neatsolutionslab/compiling-environment-containers/jvm10.0.2-kotlin1.2.51

before_script:
- source ~/.sdkman/bin/sdkman-init.sh

build-on-java10.0.2-kotlin1.2.51:
  stage: build
  only:
    - master
    - devel
  tags:
  - nsl-private
  - docker
  script:
  - sdk current java 10.0.2-zulu
  - sdk current kotlin 1.2.51
  - sdk current maven 3.5.3
  - mvn package -Dmaven.test.skip=true

test-on-java10.0.2-kotlin1.2.51:
  stage: test
  only:
    - master
    - devel
  tags:
  - nsl-private
  - docker
  script:
  - sdk current java 10.0.2-zulu
  - sdk current kotlin 1.2.51
  - sdk current maven 3.5.3
  - mvn verify
