image: neatsolutionslab/jdk:11.0.1open

before_script:
- source ~/.sdkman/bin/sdkman-init.sh

build-on-java11.0.1:
  stage: build
  tags:
  - docker
  script:
  - mvn package

test-on-java11.0.1:
  stage: test
  tags:
  - docker
  script:
  - mvn verify
