image: registry.gitlab.com/neatsolutionslab/compiling-environment-containers/jvm10.0.2-kotlin-1.2.51
build:
  stage: build
  script:
  - chmod +x ~/.sdkman/bin/sdkman-init.sh
  - source ~/.sdkman/bin/sdkman-init.sh; mvn package -Dmaven.test.skip=true

test:
  stage: test
  script:
  - chmod +x ~/.sdkman/bin/sdkman-init.sh
  - source ~/.sdkman/bin/sdkman-init.sh; mvn verify
