package nsl.sam.functional.multiannotation

import nsl.sam.spring.annotation.EnableSimpleAuthenticationMethods

@EnableSimpleAuthenticationMethods(debug = false)
class MultiEnabledAnnotationFunctionalTestConfigOne