package nsl.sam.functional.multiannotation

import nsl.sam.spring.annotation.EnableSimpleAuthenticationMethods

@EnableSimpleAuthenticationMethods(debug = true)
class MultiEnabledAnnotationFunctionalTestConfigOne