package nsl.sam.functional.multiannotation

import nsl.sam.spring.annotation.EnableSimpleAuthenticationMethods

@EnableSimpleAuthenticationMethods
class MultiEnabledAnnotationFunctionalTestConfigOne {
}